name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - run: npm run build --if-present
      - run: npm run test-ct

      - name: Copy Playwright report to docs folder
        run: |
          mkdir -p ./docs
          cp -r playwright-report/* ./docs/

      - name: Commit and Push changes
        run: |
          git config --global user.name "99Troniee_"
          git config --global user.email "kiradz1328@gmail.com"
          git add ./docs
          git commit -m "Add Playwright report"
          git push origin main
